<?php $_code=$this->getMethodCode() ?>
<table class="form-list datix_form_credit_card" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <tr>
        <td class="label">
            <label><?php echo $this->__('Credit Card Type') ?> <span class="required">*</span></label>
        </td>
        <?php $CcAvailableTypes = $this->getCcAvailableTypes(); ?>
        <td class="value">
            <div class="input-box">
                <div class="v-fix">
                    <select id="<?php echo $_code ?>_cc_type" name="payment[datix_cybersource_credit_card_type]" style="min-width:calc(100% - 15px);padding:5px;" title="<?php echo $this->__('Credit Card Type') ?>">
                        <option value=""><?php echo $this->__('--Please Select--')?></option>
                        <?php $_ccType = $this->getInfoData('datix_cybersource_credit_card_type') ?>
                        <?php foreach ($CcAvailableTypes as $_typeCode => $_typeName): ?>
                            <option value="<?php echo $_typeCode; ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName; ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
        </td>
    </tr>
    <tr>
        <td class="label">
            <label><?php echo $this->__('Credit Card Number') ?> <span class="required">*</span></label>
        </td>
        <td class="value">
            <div class="input-box">
                <div class="v-fix">
                    <input id="<?php echo $_code ?>_cc_number"  class="input-text validate-cc-number datixcybersource_cc_number" size="16" type="text" title="<?php echo $this->__('Credit Card Number') ?>"
                           name="payment[datix_cybersource_credit_card_number]"
                           value="<?php echo $this->htmlEscape($this->getInfoData('datix_cybersource_credit_card_number')) ?>" style="width:calc(100% - 15px);"/>
                </div>
            </div>
        </td>
    </tr>
    <tr>
        <td class="label">
            <label><?php echo $this->__('Card Verification Number') ?> <span class="required">*</span></label>
        </td>
        <td class="value">
            <div class="input-box">
                <div class="v-fix">
                    <input id="<?php echo $_code ?>_cc_cvn" class="input-text validate-cc-cvn datixcybersource_cc_cvn" size="4" type="text" title="<?php echo $this->__('Card Verification Number') ?>"
                           name="payment[datix_cybersource_card_verification_number]"
                           value="<?php echo $this->htmlEscape($this->getInfoData('datix_cybersource_card_verification_number')) ?>" style="width:100px;"/>
                </div>
            </div>
        </td>
    </tr>
    <tr>
        <td class="label">
            <label><?php echo $this->__('Expiration Date') ?> <span class="required">*</span></label>
        </td>
        <td class="value">
            <div class="input-box">
                <?php $_ccExpMonth = $this->getInfoData('datix_cybersource_expiration_date_month') ?>
                <select id="<?php echo $_code ?>_cc_expiration_mo"  title="<?php echo $this->__('Expiration Date Month') ?>" class="month validate-cc-exp cc_expiration_mo datixcybersource_cc_mo"
                        name="payment[datix_cybersource_expiration_date_month]">
                    <?php for ($currMonthInt = 1; $currMonthInt <= 12; $currMonthInt++): ?>
                        <option value="<?php echo sprintf("%02d",$currMonthInt); ?>"<?php if ( $currMonthInt == $_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo sprintf("%02d",$currMonthInt); ?></option>
                    <?php endfor; ?>
                </select> /
                <?php $_ccExpYear = $this->getInfoData('datix_cybersource_expiration_date_year') ?>
                <select id="<?php echo $_code ?>_cc_expiration_yr" title="<?php echo $this->__('Expiration Date Year') ?>" class="year cc_expiration_yr datixcybersource_cc_yr"
                        name="payment[datix_cybersource_expiration_date_year]">
                    <?php $intDateRangeLimit = date('Y',strtotime('+ 10 years')); ?>
                    <?php $intDateRangeStart = date('Y'); ?>
                    <?php for ($currYearInt = $intDateRangeStart; $currYearInt <= $intDateRangeLimit; $currYearInt++): ?>
                        <option value="<?php echo $currYearInt; ?>"<?php if ( $currYearInt == $_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $currYearInt; ?></option>
                    <?php endfor; ?>
                </select>
            </div>
        </td>
    </tr>
</table>
<div>
    <?php echo $this->getMethod()->getConfigData('message'); ?>
</div>
<style type="text/css">
    .datix_form_credit_card {
        width: calc(100% + 50px);
        background-color: #E7EFEF;
        padding: 5px 10px;
        margin: 10px -15px 10px -35px;
    }
    .datix_form_credit_card tr td {
        padding-top:5px;
        padding-bottom:5px;
    }
    .datix_form_credit_card tr td.label label {
        top:5px;
        position:relative;
    }
    .datix_form_credit_card tr td .datixcybersource_cc_number,
    .datix_form_credit_card tr td .datixcybersource_cc_cvn {
        padding:5px;
    }
    .datix_form_credit_card tr td .datixcybersource_cc_mo {
        width:55px;
        padding:5px;
    }
    .datix_form_credit_card tr td .datixcybersource_cc_yr {
        width:75px;
        padding:5px;
    }
    .datix_form_credit_card td.label label {
        width:100% !important;
    }
</style>